module.exports = {
  docs: [
    {
      type: 'category',
      label: 'AI Ecosystem War',
      items: [
        'ai-war/guide',
        'ai-war/food_chain',
        'ai-war/ms_openai',
        'ai-war/perpetual_motion',
        'ai-war/limitations',
        'ai-war/claude_code',
        'ai-war/apple_counter',
        'ai-war/ai_film',
        'ai-war/xbox',
      ],
    },
    {
      type: 'category',
      label: 'Mirror Realm',
      items: [
        'mirror-realm/prologue',
        'mirror-realm/ch01',
        'mirror-realm/ch02',
        'mirror-realm/ch03',
        'mirror-realm/ch04',
        'mirror-realm/ch05',
        'mirror-realm/ch06',
        'mirror-realm/ch07',
        'mirror-realm/ch08',
        'mirror-realm/ch09',
        'mirror-realm/ch10',
        'mirror-realm/ch11',
        'mirror-realm/ch12',
        'mirror-realm/ch12b',
        'mirror-realm/ch13',
        'mirror-realm/ch14',
        'mirror-realm/ch15',
      ],
    },
    {
      type: 'category',
      label: '科技雜文 Tech Musings',
      link: {
        type: 'generated-index',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'TechNotes',
        },
      ],
    },
  ],
};
